## based on example application.yml -> https://github.com/spring-projects/spring-boot/blob/master/docs/application.yml

spring:
  application.name: CommandLineRunner
  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update